# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import game_pb2 as game__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GameList = channel.unary_unary(
                '/Game/GameList',
                request_serializer=game__pb2.GameListFilterRequest.SerializeToString,
                response_deserializer=game__pb2.GameListResponse.FromString,
                )
        self.GameDetail = channel.unary_unary(
                '/Game/GameDetail',
                request_serializer=game__pb2.GameDetailRequest.SerializeToString,
                response_deserializer=game__pb2.GameDetailInfoResp.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GameList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GameDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GameList': grpc.unary_unary_rpc_method_handler(
                    servicer.GameList,
                    request_deserializer=game__pb2.GameListFilterRequest.FromString,
                    response_serializer=game__pb2.GameListResponse.SerializeToString,
            ),
            'GameDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GameDetail,
                    request_deserializer=game__pb2.GameDetailRequest.FromString,
                    response_serializer=game__pb2.GameDetailInfoResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GameList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game/GameList',
            game__pb2.GameListFilterRequest.SerializeToString,
            game__pb2.GameListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GameDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Game/GameDetail',
            game__pb2.GameDetailRequest.SerializeToString,
            game__pb2.GameDetailInfoResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
