# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"H\n\x15GameListFilterRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x0f\n\x07keyword\x18\x03 \x01(\t\"%\n\x11GameDetailRequest\x12\x10\n\x08gameName\x18\x01 \x01(\t\"D\n\x10GameListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12!\n\x04list\x18\x02 \x03(\x0b\x32\x13.GameDetailInfoResp\"\x8a\x01\n\x12GameDetailInfoResp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tavatarUrl\x18\x02 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\t\x12\x15\n\rdownloadTimes\x18\x05 \x01(\t\x12\x0e\n\x06\x61pkUrl\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x07 \x01(\t2t\n\x04Game\x12\x35\n\x08GameList\x12\x16.GameListFilterRequest\x1a\x11.GameListResponse\x12\x35\n\nGameDetail\x12\x12.GameDetailRequest\x1a\x13.GameDetailInfoRespB\nZ\x08./;protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;proto'
  _GAMELISTFILTERREQUEST._serialized_start=14
  _GAMELISTFILTERREQUEST._serialized_end=86
  _GAMEDETAILREQUEST._serialized_start=88
  _GAMEDETAILREQUEST._serialized_end=125
  _GAMELISTRESPONSE._serialized_start=127
  _GAMELISTRESPONSE._serialized_end=195
  _GAMEDETAILINFORESP._serialized_start=198
  _GAMEDETAILINFORESP._serialized_end=336
  _GAME._serialized_start=338
  _GAME._serialized_end=454
# @@protoc_insertion_point(module_scope)
